name: FiveDuels
version: 1.0
api-version: 1.13
main: me.five.duels.FiveDuels
description: Duels plugin by five
author: five
depend: [WorldEdit]
softdepend: [Multiverse-Core]
commands:
  duels:
    description: Main duels command